# scaffold split
echo 'scaffold split'

# ZhangDDI generated_result 95245
echo '5 random scaffold split on ZhangDDI'
python random_scaffold_split.py --seed=42 --dataset=ZhangDDI --train_data_path=datachem/randomsplit/ZhangDDI_train.csv --valid_data_path=datachem/randomsplit/ZhangDDI_valid.csv --test_data_path=datachem/randomsplit/ZhangDDI_test.csv --train_output_path=datachem/scaffoldsplit/ZhangDDI_train_scaffold_0.csv --val_output_path=datachem/scaffoldsplit/ZhangDDI_valid_scaffold_0.csv --test_output_path=datachem/scaffoldsplit/ZhangDDI_test_scaffold_0.csv
python random_scaffold_split.py --seed=89 --dataset=ZhangDDI --train_data_path=datachem/randomsplit/ZhangDDI_train.csv --valid_data_path=datachem/randomsplit/ZhangDDI_valid.csv --test_data_path=datachem/randomsplit/ZhangDDI_test.csv --train_output_path=datachem/scaffoldsplit/ZhangDDI_train_scaffold_1.csv --val_output_path=datachem/scaffoldsplit/ZhangDDI_valid_scaffold_1.csv --test_output_path=datachem/scaffoldsplit/ZhangDDI_test_scaffold_1.csv
python random_scaffold_split.py --seed=7891 --dataset=ZhangDDI --train_data_path=datachem/randomsplit/ZhangDDI_train.csv --valid_data_path=datachem/randomsplit/ZhangDDI_valid.csv --test_data_path=datachem/randomsplit/ZhangDDI_test.csv --train_output_path=datachem/scaffoldsplit/ZhangDDI_train_scaffold_2.csv --val_output_path=datachem/scaffoldsplit/ZhangDDI_valid_scaffold_2.csv --test_output_path=datachem/scaffoldsplit/ZhangDDI_test_scaffold_2.csv
python random_scaffold_split.py --seed=3625 --dataset=ZhangDDI --train_data_path=datachem/randomsplit/ZhangDDI_train.csv --valid_data_path=datachem/randomsplit/ZhangDDI_valid.csv --test_data_path=datachem/randomsplit/ZhangDDI_test.csv --train_output_path=datachem/scaffoldsplit/ZhangDDI_train_scaffold_3.csv --val_output_path=datachem/scaffoldsplit/ZhangDDI_valid_scaffold_3.csv --test_output_path=datachem/scaffoldsplit/ZhangDDI_test_scaffold_3.csv
python random_scaffold_split.py --seed=2145 --dataset=ZhangDDI --train_data_path=datachem/randomsplit/ZhangDDI_train.csv --valid_data_path=datachem/randomsplit/ZhangDDI_valid.csv --test_data_path=datachem/randomsplit/ZhangDDI_test.csv --train_output_path=datachem/scaffoldsplit/ZhangDDI_train_scaffold_4.csv --val_output_path=datachem/scaffoldsplit/ZhangDDI_valid_scaffold_4.csv --test_output_path=datachem/scaffoldsplit/ZhangDDI_test_scaffold_4.csv

# ChChMiner generated_result 32500
echo '5 random scaffold split on ChChMiner'
python random_scaffold_split.py --seed=42 --dataset=ChChMiner --train_data_path=datachem/randomsplit/ChChMiner_train.csv --valid_data_path=datachem/randomsplit/ChChMiner_valid.csv --test_data_path=datachem/randomsplit/ChChMiner_test.csv --train_output_path=datachem/scaffoldsplit/ChChMiner_train_scaffold_0.csv --val_output_path=datachem/scaffoldsplit/ChChMiner_valid_scaffold_0.csv --test_output_path=datachem/scaffoldsplit/ChChMiner_test_scaffold_0.csv
python random_scaffold_split.py --seed=89 --dataset=ChChMiner --train_data_path=datachem/randomsplit/ChChMiner_train.csv --valid_data_path=datachem/randomsplit/ChChMiner_valid.csv --test_data_path=datachem/randomsplit/ChChMiner_test.csv --train_output_path=datachem/scaffoldsplit/ChChMiner_train_scaffold_1.csv --val_output_path=datachem/scaffoldsplit/ChChMiner_valid_scaffold_1.csv --test_output_path=datachem/scaffoldsplit/ChChMiner_test_scaffold_1.csv
python random_scaffold_split.py --seed=7891 --dataset=ChChMiner --train_data_path=datachem/randomsplit/ChChMiner_train.csv --valid_data_path=datachem/randomsplit/ChChMiner_valid.csv --test_data_path=datachem/randomsplit/ChChMiner_test.csv --train_output_path=datachem/scaffoldsplit/ChChMiner_train_scaffold_2.csv --val_output_path=datachem/scaffoldsplit/ChChMiner_valid_scaffold_2.csv --test_output_path=datachem/scaffoldsplit/ChChMiner_test_scaffold_2.csv
python random_scaffold_split.py --seed=3625 --dataset=ChChMiner --train_data_path=datachem/randomsplit/ChChMiner_train.csv --valid_data_path=datachem/randomsplit/ChChMiner_valid.csv --test_data_path=datachem/randomsplit/ChChMiner_test.csv --train_output_path=datachem/scaffoldsplit/ChChMiner_train_scaffold_3.csv --val_output_path=datachem/scaffoldsplit/ChChMiner_valid_scaffold_3.csv --test_output_path=datachem/scaffoldsplit/ChChMiner_test_scaffold_3.csv
python random_scaffold_split.py --seed=2145 --dataset=ChChMiner --train_data_path=datachem/randomsplit/ChChMiner_train.csv --valid_data_path=datachem/randomsplit/ChChMiner_valid.csv --test_data_path=datachem/randomsplit/ChChMiner_test.csv --train_output_path=datachem/scaffoldsplit/ChChMiner_train_scaffold_4.csv --val_output_path=datachem/scaffoldsplit/ChChMiner_valid_scaffold_4.csv --test_output_path=datachem/scaffoldsplit/ChChMiner_test_scaffold_4.csv

# DeepDDI generated_result 307538
echo '5 random scaffold split on DeepDDI'
python random_scaffold_split.py --seed=42 --dataset=DeepDDI --train_data_path=datachem/randomsplit/DeepDDI_train.csv --valid_data_path=datachem/randomsplit/DeepDDI_valid.csv --test_data_path=datachem/randomsplit/DeepDDI_test.csv --train_output_path=datachem/scaffoldsplit/DeepDDI_train_scaffold_0.csv --val_output_path=datachem/scaffoldsplit/DeepDDI_valid_scaffold_0.csv --test_output_path=datachem/scaffoldsplit/DeepDDI_test_scaffold_0.csv
python random_scaffold_split.py --seed=89 --dataset=DeepDDI --train_data_path=datachem/randomsplit/DeepDDI_train.csv --valid_data_path=datachem/randomsplit/DeepDDI_valid.csv --test_data_path=datachem/randomsplit/DeepDDI_test.csv --train_output_path=datachem/scaffoldsplit/DeepDDI_train_scaffold_1.csv --val_output_path=datachem/scaffoldsplit/DeepDDI_valid_scaffold_1.csv --test_output_path=datachem/scaffoldsplit/DeepDDI_test_scaffold_1.csv
python random_scaffold_split.py --seed=7891 --dataset=DeepDDI --train_data_path=datachem/randomsplit/DeepDDI_train.csv --valid_data_path=datachem/randomsplit/DeepDDI_valid.csv --test_data_path=datachem/randomsplit/DeepDDI_test.csv --train_output_path=datachem/scaffoldsplit/DeepDDI_train_scaffold_2.csv --val_output_path=datachem/scaffoldsplit/DeepDDI_valid_scaffold_2.csv --test_output_path=datachem/scaffoldsplit/DeepDDI_test_scaffold_2.csv
python random_scaffold_split.py --seed=3625 --dataset=DeepDDI --train_data_path=datachem/randomsplit/DeepDDI_train.csv --valid_data_path=datachem/randomsplit/DeepDDI_valid.csv --test_data_path=datachem/randomsplit/DeepDDI_test.csv --train_output_path=datachem/scaffoldsplit/DeepDDI_train_scaffold_3.csv --val_output_path=datachem/scaffoldsplit/DeepDDI_valid_scaffold_3.csv --test_output_path=datachem/scaffoldsplit/DeepDDI_test_scaffold_3.csv
python random_scaffold_split.py --seed=2145 --dataset=DeepDDI --train_data_path=datachem/randomsplit/DeepDDI_train.csv --valid_data_path=datachem/randomsplit/DeepDDI_valid.csv --test_data_path=datachem/randomsplit/DeepDDI_test.csv --train_output_path=datachem/scaffoldsplit/DeepDDI_train_scaffold_4.csv --val_output_path=datachem/scaffoldsplit/DeepDDI_valid_scaffold_4.csv --test_output_path=datachem/scaffoldsplit/DeepDDI_test_scaffold_4.csv
